// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6AssignmentMJ.Models;

namespace Mission6AssignmentMJ.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20230213173223_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission6AssignmentMJ.Models.MovieEntry", b =>
                {
                    b.Property<int>("EntryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntryID");

                    b.ToTable("MovieEntries");

                    b.HasData(
                        new
                        {
                            EntryID = 1,
                            Category = "Action/Adventure",
                            Director = "Tim Burton",
                            Edited = true,
                            LentTo = "Dave",
                            Notes = "BatMan is so cool",
                            Rating = "PG-13",
                            Title = "Batman",
                            Year = (short)1989
                        },
                        new
                        {
                            EntryID = 2,
                            Category = "Family",
                            Director = "Ron Clements",
                            Edited = false,
                            LentTo = "Molly",
                            Notes = "The ocean",
                            Rating = "PG",
                            Title = "Moana",
                            Year = (short)2016
                        },
                        new
                        {
                            EntryID = 3,
                            Category = "Horror",
                            Director = "Ruben Fleischer",
                            Edited = false,
                            LentTo = "",
                            Notes = "",
                            Rating = "R",
                            Title = "Zombieland",
                            Year = (short)2009
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
